# This file is auto-generated. Do not edit manually.

from datetime import datetime, date

'''
Field Types Summary:
=================
Field: address1                       Type: text
Field: address2                       Type: text
Field: attribution                    Type: number
Field: attribution_date               Type: datetime
Field: city                           Type: text
Field: company                        Type: text
Field: country                        Type: country
Field: date_of_birth                  Type: date
Field: debounce_email_free            Type: boolean
Field: debounce_email_verificati      Type: text
Field: email                          Type: email
Field: email_domain                   Type: text
Field: fax                            Type: tel
Field: firstname                      Type: text
Field: industry                       Type: text
Field: is_wordpress                   Type: boolean
Field: last_active                    Type: datetime
Field: lastname                       Type: text
Field: latitude                       Type: number
Field: longitude                      Type: number
Field: mobile                         Type: tel
Field: phone                          Type: tel
Field: points                         Type: number
Field: position                       Type: text
Field: preferred_locale               Type: locale
Field: scraped_source_keyphrase       Type: text
Field: state                          Type: region
Field: timezone                       Type: timezone
Field: title                          Type: lookup
Field: website                        Type: url
Field: website_analysis_date          Type: datetime
Field: website_analysis_status        Type: multiselect
Field: website_pages                  Type: number
Field: wordpress_version              Type: text
Field: zipcode                        Type: text
'''

MAUTIC_FIELDS = {
    "address1": {
        "id": "11",
        "label": "Address Line 1",
        "alias": "address1",
        "type": "text",
        "group": "core",
        "object": "lead",
        "is_fixed": "1",
        "properties": "a:0:{}",
        "default_value": "None",
        "value": "8707 Washington Blvd, Culver City, CA 90232",
        "normalizedValue": "8707 Washington Blvd, Culver City, CA 90232",
    },
    "address2": {
        "id": "12",
        "label": "Address Line 2",
        "alias": "address2",
        "type": "text",
        "group": "core",
        "object": "lead",
        "is_fixed": "1",
        "properties": "a:0:{}",
        "default_value": "None",
        "value": "None",
        "normalizedValue": "",
    },
    "attribution": {
        "id": "21",
        "label": "Attribution",
        "alias": "attribution",
        "type": "number",
        "group": "core",
        "object": "lead",
        "is_fixed": "1",
        "properties": "a:2:{s:9:"roundmode";i:4;s:5:"scale";i:2;}",
        "default_value": "None",
        "value": "None",
        "normalizedValue": "",
    },
    "attribution_date": {
        "id": "20",
        "label": "Attribution Date",
        "alias": "attribution_date",
        "type": "datetime",
        "group": "core",
        "object": "lead",
        "is_fixed": "1",
        "properties": "a:0:{}",
        "default_value": "None",
        "value": "None",
        "normalizedValue": "",
    },
    "city": {
        "id": "13",
        "label": "City",
        "alias": "city",
        "type": "text",
        "group": "core",
        "object": "lead",
        "is_fixed": "1",
        "properties": "a:0:{}",
        "default_value": "None",
        "value": "None",
        "normalizedValue": "",
    },
    "company": {
        "id": "4",
        "label": "Primary company",
        "alias": "company",
        "type": "text",
        "group": "core",
        "object": "lead",
        "is_fixed": "1",
        "properties": "a:0:{}",
        "default_value": "None",
        "value": "None",
        "normalizedValue": "",
    },
    "country": {
        "id": "16",
        "label": "Country",
        "alias": "country",
        "type": "country",
        "group": "core",
        "object": "lead",
        "is_fixed": "1",
        "properties": "a:0:{}",
        "default_value": "None",
        "value": "None",
        "normalizedValue": "",
    },
    "date_of_birth": {
        "id": "60",
        "label": "Date of Birth",
        "alias": "date_of_birth",
        "type": "date",
        "group": "core",
        "object": "lead",
        "is_fixed": "0",
        "properties": "a:0:{}",
        "default_value": "None",
        "value": "1970-12-07",
        "normalizedValue": "1970-12-07",
    },
    "debounce_email_free": {
        "id": "58",
        "label": "Debounce Email Free Address or Not",
        "alias": "debounce_email_free",
        "type": "boolean",
        "group": "core",
        "object": "lead",
        "is_fixed": "0",
        "properties": "a:2:{s:2:"no";s:2:"No";s:3:"yes";s:3:"Yes";}",
        "default_value": "None",
        "value": "None",
        "normalizedValue": "",
    },
    "debounce_email_verificati": {
        "id": "59",
        "label": "DeBounce Email Verification Reason",
        "alias": "debounce_email_verificati",
        "type": "text",
        "group": "core",
        "object": "lead",
        "is_fixed": "0",
        "properties": "a:0:{}",
        "default_value": "None",
        "value": "Deliverable",
        "normalizedValue": "Deliverable",
    },
    "email": {
        "id": "6",
        "label": "Email",
        "alias": "email",
        "type": "email",
        "group": "core",
        "object": "lead",
        "is_fixed": "1",
        "properties": "a:0:{}",
        "default_value": "None",
        "value": "todd@designpublicgroup.com",
        "normalizedValue": "todd@designpublicgroup.com",
    },
    "email_domain": {
        "id": "61",
        "label": "Email Domain",
        "alias": "email_domain",
        "type": "text",
        "group": "core",
        "object": "lead",
        "is_fixed": "0",
        "properties": "a:0:{}",
        "default_value": "None",
        "value": "designpublicgroup.com",
        "normalizedValue": "designpublicgroup.com",
    },
    "fax": {
        "id": "10",
        "label": "Fax",
        "alias": "fax",
        "type": "tel",
        "group": "core",
        "object": "lead",
        "is_fixed": "0",
        "properties": "a:0:{}",
        "default_value": "None",
        "value": "None",
        "normalizedValue": "",
    },
    "firstname": {
        "id": "2",
        "label": "First Name",
        "alias": "firstname",
        "type": "text",
        "group": "core",
        "object": "lead",
        "is_fixed": "1",
        "properties": "a:0:{}",
        "default_value": "None",
        "value": "None",
        "normalizedValue": "",
    },
    "industry": {
        "id": "62",
        "label": "Industry",
        "alias": "industry",
        "type": "text",
        "group": "core",
        "object": "lead",
        "is_fixed": "0",
        "properties": "a:0:{}",
        "default_value": "None",
        "value": "None",
        "normalizedValue": "",
    },
    "is_wordpress": {
        "id": "55",
        "label": "Is WordPress",
        "alias": "is_wordpress",
        "type": "boolean",
        "group": "core",
        "object": "lead",
        "is_fixed": "0",
        "properties": "a:2:{s:2:"no";s:2:"No";s:3:"yes";s:3:"Yes";}",
        "default_value": "None",
        "value": "None",
        "normalizedValue": "",
    },
    "last_active": {
        "id": "19",
        "label": "Date Last Active",
        "alias": "last_active",
        "type": "datetime",
        "group": "core",
        "object": "lead",
        "is_fixed": "1",
        "properties": "a:0:{}",
        "default_value": "None",
        "value": "None",
        "normalizedValue": "",
    },
    "lastname": {
        "id": "3",
        "label": "Last Name",
        "alias": "lastname",
        "type": "text",
        "group": "core",
        "object": "lead",
        "is_fixed": "1",
        "properties": "a:0:{}",
        "default_value": "None",
        "value": "None",
        "normalizedValue": "",
    },
    "latitude": {
        "id": "63",
        "label": "Latitude",
        "alias": "latitude",
        "type": "number",
        "group": "core",
        "object": "lead",
        "is_fixed": "0",
        "properties": "a:2:{s:9:"roundmode";s:1:"3";s:5:"scale";s:0:"";}",
        "default_value": "None",
        "value": "None",
        "normalizedValue": "",
    },
    "longitude": {
        "id": "64",
        "label": "Longitude",
        "alias": "longitude",
        "type": "number",
        "group": "core",
        "object": "lead",
        "is_fixed": "0",
        "properties": "a:2:{s:9:"roundmode";s:1:"3";s:5:"scale";s:0:"";}",
        "default_value": "None",
        "value": "None",
        "normalizedValue": "",
    },
    "mobile": {
        "id": "7",
        "label": "Mobile",
        "alias": "mobile",
        "type": "tel",
        "group": "core",
        "object": "lead",
        "is_fixed": "1",
        "properties": "a:0:{}",
        "default_value": "None",
        "value": "None",
        "normalizedValue": "",
    },
    "phone": {
        "id": "8",
        "label": "Phone",
        "alias": "phone",
        "type": "tel",
        "group": "core",
        "object": "lead",
        "is_fixed": "1",
        "properties": "a:0:{}",
        "default_value": "None",
        "value": "+18005066541",
        "normalizedValue": "+18005066541",
    },
    "points": {
        "id": "9",
        "label": "Points",
        "alias": "points",
        "type": "number",
        "group": "core",
        "object": "lead",
        "is_fixed": "1",
        "properties": "a:0:{}",
        "default_value": "0",
        "value": "0",
        "normalizedValue": "0",
    },
    "position": {
        "id": "5",
        "label": "Position",
        "alias": "position",
        "type": "text",
        "group": "core",
        "object": "lead",
        "is_fixed": "1",
        "properties": "a:0:{}",
        "default_value": "None",
        "value": "None",
        "normalizedValue": "",
    },
    "preferred_locale": {
        "id": "17",
        "label": "Preferred Locale",
        "alias": "preferred_locale",
        "type": "locale",
        "group": "core",
        "object": "lead",
        "is_fixed": "1",
        "properties": "a:0:{}",
        "default_value": "None",
        "value": "None",
        "normalizedValue": "",
    },
    "scraped_source_keyphrase": {
        "id": "65",
        "label": "Scraped Source Keyphrase Location",
        "alias": "scraped_source_keyphrase",
        "type": "text",
        "group": "core",
        "object": "lead",
        "is_fixed": "0",
        "properties": "a:0:{}",
        "default_value": "None",
        "value": "52855202",
        "normalizedValue": "52855202",
    },
    "state": {
        "id": "14",
        "label": "State",
        "alias": "state",
        "type": "region",
        "group": "core",
        "object": "lead",
        "is_fixed": "1",
        "properties": "a:0:{}",
        "default_value": "None",
        "value": "None",
        "normalizedValue": "",
    },
    "timezone": {
        "id": "18",
        "label": "Preferred Timezone",
        "alias": "timezone",
        "type": "timezone",
        "group": "core",
        "object": "lead",
        "is_fixed": "1",
        "properties": "a:0:{}",
        "default_value": "None",
        "value": "None",
        "normalizedValue": "",
    },
    "title": {
        "id": "1",
        "label": "Title",
        "alias": "title",
        "type": "lookup",
        "group": "core",
        "object": "lead",
        "is_fixed": "1",
        "properties": "a:1:{s:4:"list";a:3:{i:0;s:2:"Mr";i:1;s:3:"Mrs";i:2;s:4:"Miss";}}",
        "default_value": "None",
        "value": "None",
        "normalizedValue": "",
    },
    "website": {
        "id": "22",
        "label": "Website",
        "alias": "website",
        "type": "url",
        "group": "core",
        "object": "lead",
        "is_fixed": "0",
        "properties": "a:0:{}",
        "default_value": "None",
        "value": "http://designpublicgroup.com",
        "normalizedValue": "http://designpublicgroup.com",
    },
    "website_analysis_date": {
        "id": "67",
        "label": "website_analysis_date",
        "alias": "website_analysis_date",
        "type": "datetime",
        "group": "core",
        "object": "lead",
        "is_fixed": "0",
        "properties": "a:0:{}",
        "default_value": "None",
        "value": "None",
        "normalizedValue": "",
    },
    "zipcode": {
        "id": "15",
        "label": "Zip Code",
        "alias": "zipcode",
        "type": "text",
        "group": "core",
        "object": "lead",
        "is_fixed": "1",
        "properties": "a:0:{}",
        "default_value": "None",
        "value": "None",
        "normalizedValue": "",
    },
}
